# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Parallelized general linear model.
#'
#' @export
QuickLM <- function(ys, Xs, pBigMat, observations, npcs, nqtn) {
    .Call('FarmCPUpp_QuickLM', PACKAGE = 'FarmCPUpp', ys, Xs, pBigMat, observations, npcs, nqtn)
}

